/*
 * ZUNO_CoreDefs.h
 *
 *  Created on: 30 нояб. 2020 г.
 *      Author: alexanderpolyakov
 */

#ifndef SRC_ZUNO_COREDEFS_H_
#define SRC_ZUNO_COREDEFS_H_
#include <stdint.h>

#define MAX_SYS_PARAMS 8

enum {
	ZUNO_SYSFUNC_DELAY_MS,
	ZUNO_SYSFUNC_MILLIS,
	ZUNO_SYSFUNC_EEPROM_IO,
	ZUNO_SYSFUNC_EEPROM_ERASE,
	ZUNO_SYSFUNC_COMMIT_CONFIG,
	ZUNO_SYSFUNC_LEARN,
	ZUNO_SYSFUNC_SENDPACKET,
	ZUNO_SYSFUNC_GECKOEXT_CMUCLOCK,
	ZUNO_SYSFUNC_SLEEP_CONTROL,
	ZUNO_SYSFUNC_WUP_CONTROL,
	ZUNO_SYSFUNC_MSGQUEUE_ALLOC,
	ZUNO_SYSFUNC_MSGQUEUE_SEND,
	ZUNO_SYSFUNC_MSGQUEUE_RCV,
	ZUNO_SYSFUNC_THREAD_CREATE,
	ZUNO_SYSFUNC_THREAD_SUSPEND,
	ZUNO_SYSFUNC_THREAD_RESUME,
	ZUNO_SYSFUNC_THREAD_GETCURRENTHANDLE,
	ZUNO_SYSFUNC_THREAD_ISRUNNING,
	ZUNO_SYSFUNC_THREAD_YIELD,
	ZUNO_SYSFUNC_ENTER_CRITICAL,
	ZUNO_SYSFUNC_EXIT_CRITICAL,
	ZUNO_SYSFUNC_INT_CONTROL,
	ZUNO_SYSFUNC_INT_CLEARPENDING,
	ZUNO_SYSFUNC_INT_SETPRIORITY,
    ZUNO_SYSFUNC_DMA_XFER,
    ZUNO_SYSFUNC_DMA_STOP,
    ZUNO_SYSFUNC_DMA_IS_PRC,
    ZUNO_SYSFUNC_DMA_COUNT,
	ZUNO_SYSFUNC_MAX_NUMBER,
	ZUNO_SYSFUNC_TEST = 0xFE
};

typedef struct IOQueueMsg_s{
	uint32_t 	type;
	uint32_t    param;
}  IOQueueMsg_t;

#endif /* SRC_ZUNO_COREDEFS_H_ */
