#ifndef ZUNO_DEFINITIONS
#define ZUNO_DEFINITIONS
#include "ZUNO_AutoDef.h"

#define MAX_CHANNEL_PARAMS                              4
#define ZUNO_MAX_MULTI_CHANNEL_NUMBER 					32
#define ZUNO_MAX_ASSOC_NUMBER 							32
#define ZUNO_MAX_ASSOC_NUMBER_LIMITATION				16
#define ZUNO_NAX_CCS_FOR_CHANNEL                        2
#define ZUNO_MAX_CCTYPES                                8
#define ZUNO_CODE_START                                 0x30000L
#define USER_SPACE_FLASH_ADDR                           0x10000
#define ZUNO_CUSTOM_CODESPACE_SIZE                      (0xA000-0x100)
#define MAX_ZUNO_PWMS           						4
#define MAX_AVAILIABLE_SYSHANDLERS 						32
#define MAX_ZWTRANSPORT_ENCAP							8
#define MAX_SYS_PARAMS 									8
#define ZUNO_SYSCALL_ADDR								(0x0002FF81)


enum {
	ZUNO_FUNC_DELAY_MS,
	ZUNO_FUNC_SERIAL_BEGIN,
	ZUNO_FUNC_SERIAL_END,
	ZUNO_FUNC_SERIAL_AVAILABLE,
	ZUNO_FUNC_SERIAL_READ,
	ZUNO_FUNC_SERIAL_WRITE,
	ZUNO_FUNC_MILLIS,
	ZUNO_FUNC_EEPROM_IO,
	ZUNO_FUNC_EEPROM_ERASE,
	ZUNO_FUNC_COMMIT_CONFIG,
	ZUNO_FUNC_LEARN,
	ZUNO_FUNC_SENDPACKET,
	ZUNO_FUNC_GECKOEXT_CMUCLOCK,
	ZUNO_FUNC_SLEEP_CONTROL,
	ZUNO_FUNC_WUP_CONTROL,
	ZUNO_MSGQUEUE_ALLOC,
	ZUNO_MSGQUEUE_SEND,
	ZUNO_MSGQUEUE_RCV,
	ZUNO_THREAD_CREATE,
	ZUNO_THREAD_SUSPEND,
	ZUNO_THREAD_RESUME,
	ZUNO_THREAD_GETCURRENTHANDLE,
	ZUNO_FUNC_MAX_NUMBER,
	ZUNO_FUNC_TEST = 0xFE
};
enum {
	ZUNO_EEPROM_OK,
	ZUNO_EEPROM_NOTALIGNED,
	ZUNO_EEPROM_OUT_OF_MEM,
	ZUNO_EEPROM_LOCKED,
	ZUNO_EEPROM_TIMEOUT,
	ZUNO_EEPROM_UNKNOWN
};

enum {
    ZUNO_JUMPTBL_SETUP,
    ZUNO_JUMPTBL_LOOP,
    ZUNO_JUMPTBL_CMDHANDLER,
	ZUNO_JUMPTBL_SYSTIMER,
	ZUNO_JUMPTBL_SYSEVENT,
	ZUNO_JUMPTBL_IRQ,
	ZUNO_JUMPTBL_SLEEP,
	ZUNO_JUMPTBL_WUP
};

enum {
    CMU_CLOCK_SUBFUNC_GETFREQ,
    CMU_CLOCK_SUBFUNC_ENABLE
};

enum {
    CMU_CLOCK_TYPE_HFPER,
    CMU_CLOCK_TYPE_ADC0,
    CMU_CLOCK_TYPE_TIMER0,
    CMU_CLOCK_TYPE_TIMER1,
    CMU_CLOCK_TYPE_I2C0,
	CMU_CLOCK_TYPE_I2C1,
	CMU_CLOCK_TYPE_USART0,
	CMU_CLOCK_TYPE_USART1,
	CMU_CLOCK_TYPE_USART2,
	CMU_CLOCK_TYPE_GPIO,
	CMU_CLOCK_TYPE_CSEN_HF,
	CMU_CLOCK_TYPE_CSEN_LF,
	CMU_CLOCK_TYPE_WTIMER0,
	CMU_CLOCK_TYPE_LDMA
};
enum {
    ZUNO_UNKNOWN_CMD,
    ZUNO_COMMAND_PROCESSED,
    ZUNO_COMMAND_ANSWERED,
	ZUNO_COMMAND_UNPACKED,
	ZUNO_COMMAND_BLOCKED
};

enum{
    ZUNO_CFG_DENIED,
    ZUNO_CFG_THESAME,
    ZUNO_CFG_NEW
};
enum {
	ZUNO_MODE_ALWAYS_LISTENING_NUMBER,				//0
	ZUNO_MODE_WAKE_UP_NUMBER,						//1
	ZUNO_MODE_FLIRS_NUMBER,							//2
};

enum 
{	
	ZUNO_WAKEUP_REASON_PIN         = 0,   /**< Reset triggered by reset pin */
    ZUNO_WAKEUP_REASON_WUP_EM4     = 1,   /**< Reset triggered by wake up by timer from deep sleep state  */
//Legacy: ZW_WAKEUP_SENSOR = 2,   /**< Wake up by a Wakeup Beam */
  	ZUNO_WAKEUP_REASON_WATCH_DOG    = 3,   /**< Reset triggered by watchdog */
  	ZUNO_WAKEUP_REASON_EXT_EM4      = 4,
	ZUNO_WAKEUP_REASON_POR          = 5,   /**< Reset triggered by external interrupt event in deep sleep state */
//Legacy: ZW_WAKEUP_USB_SUSPEND= 6  /**< Wake up by USB suspend */
    ZUNO_WAKEUP_REASON_SOFTRESET    = 7,   /**< Reset triggered by software */
//Legacy: ZW_WAKEUP_EMRG_WD_RESET= 8,  /**< Wake up by emergency watchdog reset */
    ZUNO_WAKEUP_REASON_BROWNOUT    = 9,   /**< Reset triggered by brownout circuit */
    ZUNO_WAKEUP_REASON_OTHER       = 0xFF /**< Reset triggered by none of the above */
};
#define ZUNO_ASSOC_NO_PARAMS 							0x00

enum
{
	CHANNEL_HANDLER_EMPTY,      // DEFAULT_VALUE
	CHANNEL_HANDLER_SINGLE_GETTER,
	CHANNEL_HANDLER_SINGLE_GETTERSETTER,
	CHANNEL_HANDLER_SINGLE_VALUEMAPPER,
	CHANNEL_HANDLER_MULTI_GETTER,
	CHANNEL_HANDLER_MULTI_GETTERSETTER,
	CHANNEL_HANDLER_MULTI_MAPPER,
	CHANNEL_HANDLER_SINGLE_GETTERSETTER_2P,
	CHANNEL_HANDLER_MULTI_GETTERSETTER_2P,
	CHANNEL_HANDLER_SINGLE_THERMOSTAT,
	CHANNEL_HANDLER_MULTI_THERMOSTAT
};

enum{
    SECURITY_KEY_S2_UNAUTHENTICATED_BIT=0x01,
    SECURITY_KEY_S2_AUTHENTICATED_BIT=0x02,
    SECURITY_KEY_S2_ACCESS_BIT=0x04,
    SECURITY_KEY_S0_BIT=0x80
};
enum {
	CHANNEL_TYPE_FLAGS_EMPTY=0,
	CHANNEL_TYPE_FLAGS_UNSECURE_AVALIABLE=0x01,
	CHANNEL_TYPE_FLAGS_IN_USE = 0x80
};

enum {
	DEVICE_CONFIGURATION_FLAGS_SLEEP = 0x01,
	DEVICE_CONFIGURATION_FLAGS_FLIRS = 0x02
};
enum{
	HEADER_FLAGS_DBG = 0x10,
	HEADER_FLAGS_NOLEDS = 0x20
};
#define DEVICE_CONFIGURATION_FLAGS_MASK_SLEEP  0x03
enum{
	ZUNO_SYS_EVENT_START 	= 0x00,
	ZUNO_SYS_EVENT_GOSLEEP 	= 0x01,
	ZUNO_SYS_EVENT_SETDEFAULT = 0x11,
	ZUNO_SYS_EVENT_LEARNCOMPLETED = 0x12,
	ZUNO_SYS_EVENT_EEPROMRESET = 0x13,
	ZUNO_SYS_EVENT_LEARNSTARTED = 0x14,
	ZUNO_SYS_EVENT_FWAUTH     = 0x15,
	ZUNO_SYS_EVENT_QUEUE_OVERLOAD   	= 0xC0,
	ZUNO_SYS_EVENT_INVALID_TX_REQUEST = 0xD0,
	ZUNO_SYS_EVENT_INVALID_COMMAND = 0xD1

};
enum {
	ZUNO_HANDLER_SYSTIMER,
	ZUNO_HANDLER_SYSEVENT,
	ZUNO_HANDLER_IRQ,
	ZUNO_HANDLER_SLEEP,
	ZUNO_HANDLER_WUP,
	ZUNO_HANDLER_DEBUGPRINT, 
	ZUNO_HANDLER_ZW_CFG,
	ZUNO_HANDLER_ZW_BATTERY,
	ZUNO_HANDLER_REPORT,
	ZUNO_HANDLER_EXTINT,
	ZUNO_HANDLER_GPT,
	ZUNO_HANDLER_MAX_NUMBER
};
enum{
	ZUNO_DBGPRT_SYS,	
	ZUNO_DBGPRT_CUSTOM_ERR,
	ZUNO_DBGPRT_CUSTOM_WARN,
	ZUNO_DBGPRT_CUSTOM_INFO,
	ZUNO_DBGPRT_CUSTOM_DBG
};
enum{
	ZUNO_PACKETFLAGS_GROUP = 0x80,
	ZUNO_PACKETFLAGS_RESEVED = 0x01
};
enum {
	ZUNO_IRQVEC_GPIO_ODD,
	ZUNO_IRQVEC_GPIO_EVEN,
	ZUNO_IRQVEC_I2C0,
	ZUNO_IRQVEC_I2C1,
	ZUNO_IRQVEC_TIMER0,
	ZUNO_IRQVEC_TIMER1,
	ZUNO_IRQVEC_WTIMER0,
	ZUNO_IRQVEC_CSEN,
	ZUNO_IRQVEC_LDMA,
	ZUNO_IRQVEC_USART0_RX,
	ZUNO_IRQVEC_USART1_RX,
	ZUNO_IRQVEC_USART2_RX
};

#define LEARN_TIMEOUT_INF 	0
#define LEARN_TIMEOUT_STOP 	0xFF

#define ZWAVE_CHANNEL_MAPPED_BIT 0x80

/* Transmit frame option flags */
#define TRANSMIT_OPTION_ACK                     0x01    /* request acknowledge from destination node */
#define TRANSMIT_OPTION_LOW_POWER               0x02    /* transmit at low output power level (1/3 of normal RF range)*/
#define TRANSMIT_OPTION_MULTICAST_AS_BROADCAST  0x02    /* The multicast frame should be send as a broadcast */
#define TRANSMIT_OPTION_AUTO_ROUTE              0x04    /* request retransmission via repeater nodes */
/* do not use response route - Even if available */
#define TRANSMIT_OPTION_NO_ROUTE                0x10
/* Use explore frame if needed */
#define TRANSMIT_OPTION_EXPLORE                 0x20
#define ZWAVE_PLUS_TX_OPTIONS 					(TRANSMIT_OPTION_ACK | TRANSMIT_OPTION_AUTO_ROUTE | TRANSMIT_OPTION_EXPLORE)


// ----------------------------------------------------------
// CHANNELS CONFIGURAION HELPERS/CONSTANTS 
// ----------------------------------------------------------

// Sensor Binary types
#define ZUNO_SENSOR_BINARY_TYPE_GENERAL_PURPOSE 		0x01
#define ZUNO_SENSOR_BINARY_TYPE_SMOKE 					0x02
#define ZUNO_SENSOR_BINARY_TYPE_CO 						0x03
#define ZUNO_SENSOR_BINARY_TYPE_CO2 					0x04
#define ZUNO_SENSOR_BINARY_TYPE_HEAT 					0x05
#define ZUNO_SENSOR_BINARY_TYPE_WATER 					0x06
#define ZUNO_SENSOR_BINARY_TYPE_FREEZE 					0x07
#define ZUNO_SENSOR_BINARY_TYPE_TAMPER 					0x08
#define ZUNO_SENSOR_BINARY_TYPE_AUX 					0x09
#define ZUNO_SENSOR_BINARY_TYPE_DOOR_WINDOW 			0x0a
#define ZUNO_SENSOR_BINARY_TYPE_TILT 					0x0b
#define ZUNO_SENSOR_BINARY_TYPE_MOTION 					0x0c
#define ZUNO_SENSOR_BINARY_TYPE_GLASSBREAK 				0x0d
#define ZUNO_SENSOR_BINARY_TYPE_HOME_HEALTH 			0x0e
#define ZUNO_SENSOR_BINARY_TYPE_SIREN	 				0x0f
#define ZUNO_SENSOR_BINARY_TYPE_WATER_VALVE 			0x10
#define ZUNO_SENSOR_BINARY_TYPE_WEATHER_ALARM 			0x11
#define ZUNO_SENSOR_BINARY_TYPE_IRRIGATION 				0x12
#define ZUNO_SENSOR_BINARY_TYPE_GAS_COMBUSTIBLE 		0x13
#define ZUNO_SENSOR_BINARY_TYPE_GAS_TOXIC 				0x14
/*
#define NOTIFICATION_SET_HOME_HEALTH_V7                                                  0x0D
#define NOTIFICATION_SET_SIREN_V7                                                        0x0E
#define NOTIFICATION_SET_WATER_VALVE_V7                                                  0x0F
#define NOTIFICATION_SET_WEATHER_ALARM_V7                                                0x10
#define NOTIFICATION_SET_IRRIGATION_V7                                                   0x11
#define NOTIFICATION_SET_GAS_ALARM_V7
*/

// Notifications
//Notification types
#define NOTIFICATION_TYPE_SMOKE_ALARM					0x01
#define NOTIFICATION_TYPE_CO_ALARM 						0x02
#define NOTIFICATION_TYPE_CO2_ALARM						0x03
#define NOTIFICATION_TYPE_HEAT_ALARM					0x04
#define NOTIFICATION_TYPE_WATER_ALARM 					0x05
#define NOTIFICATION_TYPE_ACCESS_CONTROL_ALARM			0x06
#define NOTIFICATION_TYPE_BURGLAR_ALARM					0x07
#define NOTIFICATION_TYPE_POWER_MANAGEMENT_ALARM		0x08
#define NOTIFICATION_TYPE_SYSTEM_ALARM 					0x09
#define NOTIFICATION_TYPE_EMERGENCY_ALARM				0x0a
#define NOTIFICATION_TYPE_CLOCK_ALARM					0x0b
#define NOTIFICATION_TYPE_APPLIANCE_ALARM				0x0c
#define NOTIFICATION_TYPE_HOME_HEALTH					0x0d
#define NOTIFICATION_TYPE_SIREN							0x0e
#define NOTIFICATION_TYPE_WATER_VALVE					0x0f
#define NOTIFICATION_TYPE_WEATHER_ALAR					0x10
#define NOTIFICATION_TYPE_IRRIGATION					0x11
#define NOTIFICATION_TYPE_GAS_ALARM						0x12

/*
#define NOTIFICATION_SET_HOME_HEALTH_V7                                                  0x0D
#define NOTIFICATION_SET_SIREN_V7                                                        0x0E
#define NOTIFICATION_SET_WATER_VALVE_V7                                                  0x0F
#define NOTIFICATION_SET_WEATHER_ALARM_V7                                                0x10
#define NOTIFICATION_SET_IRRIGATION_V7                                                   0x11
#define NOTIFICATION_SET_GAS_ALARM_V7                                                    0x12
*/
#define NOTIFICATION_ON_VALUE							0xff
#define NOTIFICATION_OFF_VALUE							0x00
//Notification events (UL=Unknown Location)
#define NOTIFICATION_UNKNOWN_EVENT						0xfe
//Smoke
#define NOTIFICATION_EVENT_SMOKE						0x01
#define NOTIFICATION_EVENT_SMOKE_UL						0x02
#define NOTIFICATION_EVENT_SMOKE_TEST					0x03
//CO
#define NOTIFICATION_EVENT_CO							0x01
#define NOTIFICATION_EVENT_CO_UL						0x02
#define NOTIFICATION_EVENT_CO_TEST						0x03
//CO2
#define NOTIFICATION_EVENT_CO2							0x01
#define NOTIFICATION_EVENT_CO2_UL						0x02
//HEAT
#define NOTIFICATION_EVENT_OVERHEAT						0x01
#define NOTIFICATION_EVENT_OVERHEAT_UL					0x02
#define NOTIFICATION_EVENT_TEMP_RISE					0x03
#define NOTIFICATION_EVENT_TEMP_RISE_UL					0x04
#define NOTIFICATION_EVENT_UNDERHEAT					0x05
#define NOTIFICATION_EVENT_UNDERHEAT_UL					0x06
//WATER
#define NOTIFICATION_EVENT_WATER_LEAK					0x01
#define NOTIFICATION_EVENT_WATER_LEAK_UL				0x02
#define NOTIFICATION_EVENT_WATER_LEVEL_DROP				0x03
#define NOTIFICATION_EVENT_WATER_LEVEL_DROP_UL			0x04
//ACCESS
#define NOTIFICATION_EVENT_MANUAL_LOCK					0x01
#define NOTIFICATION_EVENT_MANUAL_UNLOCK				0x02
#define NOTIFICATION_EVENT_MANUAL_NOT_FULLY_LOCKED		0x07
#define NOTIFICATION_EVENT_RF_LOCK						0x03
#define NOTIFICATION_EVENT_RF_UNLOCK					0x04
#define NOTIFICATION_EVENT_RF_NOT_FULLY_LOCKED			0x08
#define NOTIFICATION_EVENT_KEYPAD_LOCK					0x05
#define NOTIFICATION_EVENT_KEYPAD_UNLOCK				0x06
#define NOTIFICATION_EVENT_AUTO_LOCKED					0x09
#define NOTIFICATION_EVENT_AUTO_LOCK_NOT_FULLY_LOCKED	0x0a
#define NOTIFICATION_EVENT_LOCK_JAMMED					0x0b
#define NOTIFICATION_EVENT_ALL_USER_CODES_DELETED		0x0c
#define NOTIFICATION_EVENT_SINGLE_USER_CODE_DELETED		0x0d
#define NOTIFICATION_EVENT_NEW_USER_CODE_ADDED			0X0e
#define NOTIFICATION_EVENT_NEW_USER_CODE_NOT_ADDED		0x0f
#define NOTIFICATION_EVENT_KEYPAD_TEMPORARY_DISABLE		0x10
#define NOTIFICATION_EVENT_KEYPAD_BUSY					0x11
#define NOTIFICATION_EVENT_NEW_PROGRAM_CODE_ENTERED		0x12
#define NOTIFICATION_EVENT_MANUAL_CODE_EXCEEDS_LIMITS	0x13
#define NOTIFICATION_EVENT_RF_UNLOCK_INVALID_CODE		0x14
#define NOTIFICATION_EVENT_RF_LOCK_INVALID_CODE			0x15
#define NOTIFICATION_EVENT_WINDOW_DOOR_OPENED			0x16
#define NOTIFICATION_EVENT_WINDOW_DOOR_CLOSED			0x17
//BURGLAR, HOME SECURITY
#define NOTIFICATION_EVENT_INTRUSION					0x01
#define NOTIFICATION_EVENT_INTRUSION_UL					0x02
#define NOTIFICATION_EVENT_TAMPER_REMOVED				0x03
#define NOTIFICATION_EVENT_TAMPER_INVALID_CODE			0x04
#define NOTIFICATION_EVENT_GLASS_BREAK					0x05
#define NOTIFICATION_EVENT_GLASS_BREAK_UL				0x06
#define NOTIFICATION_EVENT_MOTION_DETECTION				0x07
#define NOTIFICATION_EVENT_MOTION_DETECTION_UL			0x08
//POWER MANAGEMENT
#define NOTIFICATION_EVENT_POWER_APPLIED				0x01
#define NOTIFICATION_EVENT_AC_DISCONNECTED				0x02
#define NOTIFICATION_EVENT_AC_RECONNECTED				0x03
#define NOTIFICATION_EVENT_SURGE						0x04
#define NOTIFICATION_EVENT_VOLTAGE_DROP					0x05
#define NOTIFICATION_EVENT_OVER_CURRENT					0x06
#define NOTIFICATION_EVENT_OVER_VOLTAGE					0x07
#define NOTIFICATION_EVENT_OVER_LOAD					0x08
#define NOTIFICATION_EVENT_LOAD_ERROR					0x09
#define NOTIFICATION_EVENT_REPLACE_BAT_SOON				0x0a
#define NOTIFICATION_EVENT_REPLACE_BAT_NOW				0x0b
//SYSTEM
#define NOTIFICATION_EVENT_HW_FAIL						0x01
#define NOTIFICATION_EVENT_SW_FAIL						0x02
#define NOTIFICATION_EVENT_HW_FAIL_OEM					0x03
#define NOTIFICATION_EVENT_SW_FAIL_OEM					0x04
//EMERGENCY_ALARM
#define NOTIFICATION_EVENT_CONTACT_POLICE				0x01
#define NOTIFICATION_EVENT_CONTACT_FIREMEN				0x02
#define NOTIFICATION_EVENT_CONTACT_MEDIC				0x03
//CLOCK
#define NOTIFICATION_EVENT_WAKE_UP_ALERT				0x01
#define NOTIFICATION_EVENT_TIMER_ENDED					0x02
// GAS
#define NOTIFICATION_EVENT_GAS_COMBUSTIBLE				0x02
#define NOTIFICATION_EVENT_GAS_TOXIC					0x04

// Meter
#define ZUNO_METER_TYPE_ELECTRIC	                    0x01
#define ZUNO_METER_TYPE_GAS		                        0x02
#define ZUNO_METER_TYPE_WATER		                    0x03
#define ZUNO_METER_RESETABLE		                    0x80
#define ZUNO_METER_ELECTRIC_SCALE_KWH	                 0x00
#define ZUNO_METER_ELECTRIC_SCALE_KVAH		             0x01
#define ZUNO_METER_ELECTRIC_SCALE_WATTS		             0x02
#define ZUNO_METER_ELECTRIC_SCALE_PULSECOUNT		     0x03
#define ZUNO_METER_ELECTRIC_SCALE_VOLTS		     		 0x04
#define ZUNO_METER_ELECTRIC_SCALE_AMPS		     		 0x05
#define ZUNO_METER_ELECTRIC_SCALE_POWERFACTOR		     0x06
#define ZUNO_METER_ELECTRIC_SCALE_MST		  			 0x07
#define ZUNO_METER_GAS_SCALE_METERS3	                 0x00
#define ZUNO_METER_GAS_SCALE_FEET3		             	 0x01
#define ZUNO_METER_GAS_SCALE_PULSECOUNT		    		 0x03
#define ZUNO_METER_WATER_SCALE_METERS3	                 0x00
#define ZUNO_METER_WATER_SCALE_FEET3		             0x01
#define ZUNO_METER_WATER_SCALE_GALLONS		             0x02
#define ZUNO_METER_WATER_SCALE_PULSECOUNT		    	 0x03
#define ZUNO_METER_WATER_SCALE_MST		    	 		 0x07
#define METER_PRECISION_ZERO_DECIMALS 					 0x00
#define METER_PRECISION_ONE_DECIMAL 					 0x01
#define METER_PRECISION_TWO_DECIMALS 					 0x02
#define METER_PRECISION_THREE_DECIMALS 					 0x03
#define METER_RESET_ENABLE 								 0x01
#define METER_RESET_DISABLE 							 0x00
#define METER_SIZE_ONE_BYTE 							 0x01
#define METER_SIZE_TWO_BYTES 							 0x02
#define METER_SIZE_FOUR_BYTES 							 0x04
#define METER_PROPERTIES_COMBINER(SCALE,SIZE,PRECISION) \
			(((SIZE-1) & 0x03) << 6)| \
			((SCALE & 0x07)) | \
			((PRECISION & 0x07) << 3)

#define METER_EMPTY_RESETTER							




// Sensor Multilevel types
#define ZUNO_SENSOR_MULTILEVEL_TYPE_TEMPERATURE		                                   	0x01
#define ZUNO_SENSOR_MULTILEVEL_TYPE_GENERAL_PURPOSE_VALUE		                        0x02
#define ZUNO_SENSOR_MULTILEVEL_TYPE_LUMINANCE		                                    0x03
#define ZUNO_SENSOR_MULTILEVEL_TYPE_POWER		                                        0x04
#define ZUNO_SENSOR_MULTILEVEL_TYPE_RELATIVE_HUMIDITY		                            0x05
#define ZUNO_SENSOR_MULTILEVEL_TYPE_VELOCITY		                                    0x06
#define ZUNO_SENSOR_MULTILEVEL_TYPE_DIRECTION		                                    0x07
#define ZUNO_SENSOR_MULTILEVEL_TYPE_ATMOSPHERIC_PRESSURE		                        0x08
#define ZUNO_SENSOR_MULTILEVEL_TYPE_BAROMETRIC_PRESSURE		                           	0x09
#define ZUNO_SENSOR_MULTILEVEL_TYPE_SOLAR_RADIATION		                               	0x0A
#define ZUNO_SENSOR_MULTILEVEL_TYPE_DEW_POINT		                                    0x0B
#define ZUNO_SENSOR_MULTILEVEL_TYPE_RAIN_RATE		                                    0x0C
#define ZUNO_SENSOR_MULTILEVEL_TYPE_TIDE_LEVEL		                                    0x0D
#define ZUNO_SENSOR_MULTILEVEL_TYPE_WEIGHT		                                        0x0E
#define ZUNO_SENSOR_MULTILEVEL_TYPE_VOLTAGE		                                       	0x0F
#define ZUNO_SENSOR_MULTILEVEL_TYPE_CURRENT		                                       	0x10
#define ZUNO_SENSOR_MULTILEVEL_TYPE_CO2_LEVEL		                                    0x11
#define ZUNO_SENSOR_MULTILEVEL_TYPE_AIR_FLOW		                                    0x12
#define ZUNO_SENSOR_MULTILEVEL_TYPE_TANK_CAPACITY		                                0x13
#define ZUNO_SENSOR_MULTILEVEL_TYPE_DISTANCE		                                    0x14
#define ZUNO_SENSOR_MULTILEVEL_TYPE_ANGLE_POSITION		                                0x15
#define ZUNO_SENSOR_MULTILEVEL_TYPE_ROTATION                                            0x16
#define ZUNO_SENSOR_MULTILEVEL_TYPE_WATER_TEMPERATURE                                   0x17
#define ZUNO_SENSOR_MULTILEVEL_TYPE_SOIL_TEMPERATURE                                    0x18
#define ZUNO_SENSOR_MULTILEVEL_TYPE_SEISMIC_INTENSITY                                   0x19
#define ZUNO_SENSOR_MULTILEVEL_TYPE_SEISMIC_MAGNITUDE                                   0x1A
#define ZUNO_SENSOR_MULTILEVEL_TYPE_ULTRAVIOLET                                         0x1B
#define ZUNO_SENSOR_MULTILEVEL_TYPE_ELECTRICAL_RESISTIVITY                              0x1C
#define ZUNO_SENSOR_MULTILEVEL_TYPE_ELECTRICAL_CONDUCTIVITY                             0x1D
#define ZUNO_SENSOR_MULTILEVEL_TYPE_LOUDNESS                                            0x1E
#define ZUNO_SENSOR_MULTILEVEL_TYPE_MOISTURE                                            0x1F
#define ZUNO_SENSOR_MULTILEVEL_TYPE_FREQUENCY                                           0x20
#define ZUNO_SENSOR_MULTILEVEL_TYPE_TIME                                                0x21

#define ZUNO_SENSOR_MULTILEVEL_TYPE_FORMALDEHYDE_CH2O_LEVEL                             0x24
#define ZUNO_SENSOR_MULTILEVEL_TYPE_RADON_CONCENTRATION                                 0x25
#define ZUNO_SENSOR_MULTILEVEL_TYPE_METHANE_DENSITY_CH4                                 0x26
#define ZUNO_SENSOR_MULTILEVEL_TYPE_VOLATILE_ORGANIC_COMPOUND                           0x27
#define ZUNO_SENSOR_MULTILEVEL_TYPE_CARBON_MONOXIDE_CO                           		0x28

#define ZUNO_SENSOR_MULTILEVEL_TYPE_WATER_FLOW                           				0x37

//Sensor Multilevel scales,sizes,precisions
#define SENSOR_MULTILEVEL_PRECISION_ZERO_DECIMALS 									0x00
#define SENSOR_MULTILEVEL_PRECISION_ONE_DECIMAL 									0x01
#define SENSOR_MULTILEVEL_PRECISION_TWO_DECIMALS 									0x02
#define SENSOR_MULTILEVEL_SIZE_ONE_BYTE 											0x01
#define SENSOR_MULTILEVEL_SIZE_TWO_BYTES 											0x02
#define SENSOR_MULTILEVEL_SIZE_FOUR_BYTES 											0x04

// Air temperature
#define SENSOR_MULTILEVEL_SCALE_CELSIUS 											0x00 
//General purpose
#define SENSOR_MULTILEVEL_SCALE_PERCENTAGE_VALUE									0x00 
#define SENSOR_MULTILEVEL_SCALE_DIMENSIONLESS_VALUE									0x01 

//Luminance
#define SENSOR_MULTILEVEL_SCALE_LUX													0x01
//Power
#define SENSOR_MULTILEVEL_SCALE_WATT												0x00
#define SENSOR_MULTILEVEL_SCALE_BTU_PER_HOUR										0x01
//Humidity
#define SENSOR_MULTILEVEL_SCALE_PERCENTAGE_VALUE									0x00 
//Moisture
#define SENSOR_MULTILEVEL_SCALE_PERCENTAGE_VALUE									0x00
//Velocity
#define SENSOR_MULTILEVEL_SCALE_METERS_PER_SECOND	 								0x00
//Athmospheric pressure
#define SENSOR_MULTILEVEL_SCALE_KILO_PASCAL 										0x00
//Barometric pressure
#define SENSOR_MULTILEVEL_SCALE_KILOPASCAL										0x00
//Solar radiation
#define SENSOR_MULTILEVEL_SCALE_WAVELENGTH_PER_SQUARE_METER								0x00
//Dew point
#define SENSOR_MULTILEVEL_SCALE_CELSIUS											0x00
//Rain rate
#define SENSOR_MULTILEVEL_SCALE_MILLIMETERS_PER_HOUR									0x00
//Tide level
#define SENSOR_MULTILEVEL_SCALE_METER											0x00
//Weight
#define SENSOR_MULTILEVEL_SCALE_KILOGRAM										0x00
//Voltage
#define SENSOR_MULTILEVEL_SCALE_VOLT											0x00
//Current
#define SENSOR_MULTILEVEL_SCALE_AMPERE											0x00
//CO2 level
#define SENSOR_MULTILEVEL_SCALE_PARTS_PER_MILLION										0x00
//Air flow
#define SENSOR_MULTILEVEL_SCALE_CUBIC_METER_PER_HOUR									0x00
//Tank capacity
#define SENSOR_MULTILEVEL_SCALE_LITER											0x00
//Distance
#define SENSOR_MULTILEVEL_SCALE_METER											0x00
//Angle position
#define SENSOR_MULTILEVEL_SCALE_PERCENTAGE_VALUE								0x00
//Rotation
#define SENSOR_MULTILEVEL_SCALE_REVOLUTION_PER_MINUTE  							0x00
//Water temperature
#define SENSOR_MULTILEVEL_SCALE_CELSIUS											0x00
//Soil temperature
#define SENSOR_MULTILEVEL_SCALE_CELSIUS											0x00
//Seismic intensity 
#define SENSOR_MULTILEVEL_SCALE_MERCALLI										0x00
//Seismic magnitude 
#define SENSOR_MULTILEVEL_SCALE_LOCAL											0x00
//Ultraviolet
#define SENSOR_MULTILEVEL_SCALE_ULTRAVIOLET_INDEX								0x00
//Electrical conductivity 
#define SENSOR_MULTILEVEL_SCALE_SIEMENS_PER_METER								0x00
//Electrical resistivity 
#define SENSOR_MULTILEVEL_SCALE_OHM_METER										0x00
//Loudness
#define SENSOR_MULTILEVEL_SCALE_DECIBELS										0x00
//Frequency
#define SENSOR_MULTILEVEL_SCALE_HERTZ											0x00
//Time
#define SENSOR_MULTILEVEL_SCALE_SECOND											0x00
//Target temperature
#define SENSOR_MULTILEVEL_SCALE_CELSIUS											0x00
#define SENSOR_MULTILEVEL_SCALE_LITERS_PER_HOUR									0x00

//Sensor Multilevel Properties
#define SENSOR_MULTILEVEL_PROPERTIES_SIZE_MASK                                      0x07
#define SENSOR_MULTILEVEL_PROPERTIES_SCALE_SHIFT                                    0x03
#define SENSOR_MULTILEVEL_PROPERTIES_SCALE_MASK                                     0x18
#define SENSOR_MULTILEVEL_PROPERTIES_PRECISION_SHIFT                                0x05
#define SENSOR_MULTILEVEL_PROPERTIES_PRECISION_MASK                                 0xE0
#define SENSOR_MULTILEVEL_PROPERTIES_COMBINER(SCALE,SIZE,PRECISION) \
			(SIZE & SENSOR_MULTILEVEL_PROPERTIES_SIZE_MASK) | \
			((SCALE << SENSOR_MULTILEVEL_PROPERTIES_SCALE_SHIFT) & SENSOR_MULTILEVEL_PROPERTIES_SCALE_MASK) | \
			((PRECISION << SENSOR_MULTILEVEL_PROPERTIES_PRECISION_SHIFT) & SENSOR_MULTILEVEL_PROPERTIES_PRECISION_MASK)
#define MACRO_CAST_POINTER_TO_VOID(FUNCTION) 										FUNCTION //((VOID_FUNC_POINTER_VOID) FUNCTION)


// Thermostats

#define THERMOSTAT_FLAGS_OFF					0x01
#define THERMOSTAT_FLAGS_HEAT					0x02
#define THERMOSTAT_FLAGS_COOL					0x04
#define THERMOSTAT_FLAGS_FURNACE				0x08
#define THERMOSTAT_FLAGS_DRY					0x10
#define THERMOSTAT_FLAGS_MOIST					0x20
#define THERMOSTAT_FLAGS_AUTO_CHANGEOVER		0x40
#define THERMOSTAT_FLAGS_AUTO					THERMOSTAT_FLAGS_AUTO_CHANGEOVER
#define THERMOSTAT_FLAGS_FULL_POWER				0x80


#define THERMOSTAT_MODE_OFF				0x00
#define THERMOSTAT_MODE_HEAT			0x01
#define THERMOSTAT_MODE_COOL			0x02
#define THERMOSTAT_MODE_FURNACE			0x07
#define THERMOSTAT_MODE_DRY				0x08
#define THERMOSTAT_MODE_MOIST			0x09
#define THERMOSTAT_MODE_AUTO_CHANGEOVER	0x0A
#define THERMOSTAT_MODE_AUTO			THERMOSTAT_MODE_AUTO_CHANGEOVER
#define THERMOSTAT_MODE_FULL_POWER		0x0F



#define THERMOSTAT_UNITS_CELSIUS		0
#define THERMOSTAT_UNITS_FAHRENHEIT		0x80
#define THERMOSTAT_RANGE_NEG			0x20
#define THERMOSTAT_RANGE_POS			0x40
#define THERMOSTAT_LIMITS_MASK			0x1F
#define THERMOSTAT_PROPERTIES_COMBINER(UNITS, POS_NEG, LIMITS)						(UNITS | POS_NEG | (LIMITS & THERMOSTAT_LIMITS_MASK))
// Switch color
#define SWITCH_COLOR_FLAGS_WARM_WHITE	0x01
#define SWITCH_COLOR_FLAGS_COLD_WHITE 	0x02
#define SWITCH_COLOR_FLAGS_RED 			0x04
#define SWITCH_COLOR_FLAGS_GREEN 		0x08
#define SWITCH_COLOR_FLAGS_BLUE 		0x10
#define SWITCH_COLOR_FLAGS_AMBER 		0x20
#define SWITCH_COLOR_FLAGS_CYAN 		0x40
#define SWITCH_COLOR_FLAGS_PURPLE 		0x80

#define SWITCH_COLOR_COMPONENT_WARM_WHITE  0x00
#define SWITCH_COLOR_COMPONENT_COLD_WHITE  0x01
#define SWITCH_COLOR_COMPONENT_RED         0x02
#define SWITCH_COLOR_COMPONENT_GREEN       0x03
#define SWITCH_COLOR_COMPONENT_BLUE        0x04
#define SWITCH_COLOR_COMPONENT_AMBER       0x05
#define SWITCH_COLOR_COMPONENT_CYAN        0x06
#define SWITCH_COLOR_COMPONENT_PURPLE      0x07

#define ZUNO_SLEEPING_MODE_ALWAYS_AWAKE 			    ZUNO_MODE_ALWAYS_LISTENING_NUMBER
#define ZUNO_SLEEPING_MODE_SLEEPING			 		    ZUNO_MODE_WAKE_UP_NUMBER
#define ZUNO_SLEEPING_MODE_FREQUENTLY_AWAKE 		    ZUNO_MODE_FLIRS_NUMBER
#define SKETCH_FLAG_S2_UNAUTHENTICATED_BIT				SECURITY_KEY_S2_UNAUTHENTICATED_BIT
#define SKETCH_FLAG_S2_AUTHENTICATED_BIT 				SECURITY_KEY_S2_AUTHENTICATED_BIT
#define SKETCH_FLAG_S2_ACCESS_BIT						SECURITY_KEY_S2_ACCESS_BIT

#define ZUNO_AWAKETIMEOUT_SLEEPNOW                      0              
#define ZUNO_AWAKETIMEOUT_FOREVER                       0xFFFFFFFF
#define ZUNO_SLEEPLOCK_SYSTEM                           0
#define ZUNO_SLEEPLOCK_CUSTOM                           1


#ifndef ZUNO_PREPROC_PHASE

#include "Custom_defs.h"
#endif
#endif // ZUNO_DEFINITIONS