#ifndef ZUNO_DEFINITIONS
#define ZUNO_DEFINITIONS

#define ZUNO_CORE_VERSION_MAJOR  0x03
#define ZUNO_CORE_VERSION_MINOR  0x01

#define MAX_CHANNEL_PARAMS       4

#define ZUNO_MAX_MULTI_CHANNEL_NUMBER                   32
#define ZUNO_MAX_ASSOC_NUMBER                           32
#define USER_SPACE_FLASH_ADDR                           0x10000
#define ZUNO_CUSTOM_CODESPACE_SIZE                      (0xA000-0x100)

#define MAX_ZUNO_PWMS           4

enum {
   ZUNO_FUNC_UNSOLICITED_REPORT,
    ZUNO_FUNC_ASSOCIATION_SEND,
    ZUNO_FUNC_DELAY_MS,
    ZUNO_FUNC_SERIAL_BEGIN,
    ZUNO_FUNC_SERIAL_END,
    ZUNO_FUNC_SERIAL_AVAILABLE,
    ZUNO_FUNC_SERIAL_READ,
    ZUNO_FUNC_SERIAL_WRITE,
    ZUNO_FUNC_MILLIS,
    ZUNO_FUNC_SPI0_INIT,
    ZUNO_FUNC_SPI0_ENABLE,
    ZUNO_FUNC_SPI0_TRANSFER,
    ZUNO_FUNC_EEPROM_READ,
    ZUNO_FUNC_EEPROM_WRITE,
    ZUNO_FUNC_NZRAM_READ,
    ZUNO_FUNC_NZRAM_WRITE,
    ZUNO_FUNC_RADIO_POLL,
    ZUNO_FUNC_SETUP_FWUPGRADE,
    ZUNO_FUNC_COMMIT_CONFIG,
    ZUNO_FUNC_LEARN,
    ZUNO_FUNC_SPI0_TXDMA,
    ZUNO_FUNC_INT0_WUP_LEVEL,
    ZUNO_FUNC_BEAMCOUNT,
    ZUNO_FUNC_DBGSENDDATA,
    ZUNO_FUNC_CREATEPACKET,
    ZUNO_FUNC_GECKOEXT_CMUCLOCK,
    ZUNO_FUNC_TEST = 0xFE

};
enum {
    ZUNO_JUMPTBL_SETUP,
    ZUNO_JUMPTBL_LOOP,
    ZUNO_JUMPTBL_CMDHANDLER
};

enum {
    CMU_CLOCK_SUBFUNC_GETFREQ,
    CMU_CLOCK_SUBFUNC_ENABLE
};

enum {
    CMU_CLOCK_TYPE_HFPER,
    CMU_CLOCK_TYPE_ADC0,
    CMU_CLOCK_TYPE_TIMER0,
    CMU_CLOCK_TYPE_TIMER1,
};
enum {
    ZUNO_UNKNOWN_CMD,
    ZUNO_COMMAND_PROCESSED,
    ZUNO_COMMAND_ANSWERED
};

enum{
    ZUNO_CFG_DENIED,
    ZUNO_CFG_THESAME,
    ZUNO_CFG_NEW
};

#endif // ZUNO_DEFINITIONS