#ifndef _FONT_VERDANA_7_8_H
#define _FONT_VERDANA_7_8_H
//WARNING: This Font Require X-GLCD Lib.
//         You can not use it with MikroE GLCD Lib.

//Font Generated by MikroElektronika GLCD Font Creator 1.2.0.0
//MikroElektronika 2011 
//http://www.mikroe.com 

//GLCD FontName : Verdana7x8
//GLCD FontSize : 7 x 8

extern const unsigned char Verdana7x8[];
#endif