#ifndef ZUNO_DEFINITIONS
#define ZUNO_DEFINITIONS

#define ZUNO_CORE_VERSION_MAJOR  0x03
#define ZUNO_CORE_VERSION_MINOR  0x01

#define MAX_CHANNEL_PARAMS                              4
#define ZUNO_MAX_MULTI_CHANNEL_NUMBER 					32
#define ZUNO_MAX_ASSOC_NUMBER 							32
#define ZUNO_NAX_CCS_FOR_CHANNEL                        2
#define ZUNO_MAX_CCTYPES                                8

#define USER_SPACE_FLASH_ADDR                           0x10000
#define ZUNO_CUSTOM_CODESPACE_SIZE                      (0xA000-0x100)

#define MAX_ZUNO_PWMS           4

enum {
	ZUNO_FUNC_UNSOLICITED_REPORT,
	ZUNO_FUNC_ASSOCIATION_SEND,
	ZUNO_FUNC_DELAY_MS,
	ZUNO_FUNC_SERIAL_BEGIN,
	ZUNO_FUNC_SERIAL_END,
	ZUNO_FUNC_SERIAL_AVAILABLE,
	ZUNO_FUNC_SERIAL_READ,
	ZUNO_FUNC_SERIAL_WRITE,
	ZUNO_FUNC_MILLIS,
	ZUNO_FUNC_SPI0_INIT,
	ZUNO_FUNC_SPI0_ENABLE,
	ZUNO_FUNC_SPI0_TRANSFER,
	ZUNO_FUNC_EEPROM_READ,
	ZUNO_FUNC_EEPROM_WRITE,
	ZUNO_FUNC_NZRAM_READ,
	ZUNO_FUNC_NZRAM_WRITE,
	ZUNO_FUNC_SETUP_FWUPGRADE,
	ZUNO_FUNC_COMMIT_CONFIG,
	ZUNO_FUNC_LEARN,
	ZUNO_FUNC_SPI0_TXDMA,
	ZUNO_FUNC_INT0_WUP_LEVEL,
	ZUNO_FUNC_BEAMCOUNT,
	ZUNO_FUNC_SENDPACKET,
	ZUNO_FUNC_GECKOEXT_CMUCLOCK,
	ZUNO_FUNC_TEST = 0xFE
};
enum {
    ZUNO_JUMPTBL_SETUP,
    ZUNO_JUMPTBL_LOOP,
    ZUNO_JUMPTBL_CMDHANDLER,
	ZUNO_JUMPTBL_SYSEVENT,
	ZUNO_JUMPTBL_IRQ,
	ZUNO_JUMPTBL_SYSTIMER
};

enum {
    CMU_CLOCK_SUBFUNC_GETFREQ,
    CMU_CLOCK_SUBFUNC_ENABLE
};

enum {
    CMU_CLOCK_TYPE_HFPER,
    CMU_CLOCK_TYPE_ADC0,
    CMU_CLOCK_TYPE_TIMER0,
    CMU_CLOCK_TYPE_TIMER1,
    CMU_CLOCK_TYPE_I2C0
};
enum {
    ZUNO_UNKNOWN_CMD,
    ZUNO_COMMAND_PROCESSED,
    ZUNO_COMMAND_ANSWERED,
	ZUNO_COMMAND_UNPACKED,
	ZUNO_COMMAND_BLOCKED
};

enum{
    ZUNO_CFG_DENIED,
    ZUNO_CFG_THESAME,
    ZUNO_CFG_NEW
};

enum {
	ZUNO_SWITCH_BINARY_CHANNEL_NUMBER = 1, 			//0x01
	ZUNO_SWITCH_MULTILEVEL_CHANNEL_NUMBER, 			//0x02
	ZUNO_SENSOR_BINARY_CHANNEL_NUMBER, 				//0x03
	ZUNO_SENSOR_MULTILEVEL_CHANNEL_NUMBER, 			//0x04
	ZUNO_METER_CHANNEL_NUMBER, 						//0x05
	ZUNO_DOORLOCK_CHANNEL_NUMBER,					//0x06
	ZUNO_FLOWSTOP_CHANNEL_NUMBER,					//0x07
	ZUNO_SIREN_CHANNEL_NUMBER,						//0x08	
	ZUNO_BLINDS_CHANNEL_NUMBER,						//0x09
	ZUNO_THERMOSTAT_CHANNEL_NUMBER,					//0x0A
	ZUNO_SWITCH_COLOR_CHANNEL_NUMBER,				//0x0B
	ZUNO_END_OF_SUPPORTED_CC_NUM,
};
enum{
    CHANNEL_HANDLER_EMPTY,      // DEFAULT_VALUE
    CHANNEL_HANDLER_SINGLE_GETTER,
    CHANNEL_HANDLER_SINGLE_GETTERSETTER,
    CHANNEL_HANDLER_SINGLE_VALUEMAPPER,
    CHANNEL_HANDLER_MULTI_GETTER,
    CHANNEL_HANDLER_MULTI_GETTERSETTER,
    CHANNEL_HANDLER_MULTI_MAPPER
};
enum{
    SECURITY_KEY_S2_UNAUTHENTICATED_BIT=0x01,
    SECURITY_KEY_S2_AUTHENTICATED_BIT=0x02,
    SECURITY_KEY_S2_ACCESS_BIT=0x04,
    SECURITY_KEY_S0_BIT=0x80
};
enum {
	CHANNEL_TYPE_FLAGS_EMPTY=0,
	CHANNEL_TYPE_FLAGS_UNSECURE_AVALIABLE=0x01,
	CHANNEL_TYPE_FLAGS_IN_USE = 0x80
};

enum {
	DEVICE_CONFIGURATION_FLAGS_SLEEP = 0x01,
	DEVICE_CONFIGURATION_FLAGS_FLIRS = 0x02
};
enum{
	ZUNO_SYS_EVENT_START 	= 0x00,
	ZUNO_SYS_EVENT_GOSLEEP 	= 0x01,
	ZUNO_SYS_EVENT_SETDEFAULT = 0x11,
	ZUNO_SYS_EVENT_LEARNCOMPLETED = 0x12,
	ZUNO_SYS_EVENT_EEPROMRESET = 0x13,
	ZUNO_SYS_EVENT_LEARNSTARTED = 0x14,
	ZUNO_SYS_EVENT_FWAUTH     = 0x15,
	ZUNO_SYS_EVENT_QUEUE_OVERLOAD   	= 0xC0,
	ZUNO_SYS_EVENT_INVALID_TX_REQUEST = 0xD0,
	ZUNO_SYS_EVENT_INVALID_COMMAND = 0xD1

};
enum {
	ZUNO_HANDLER_SYSTIMER,
	ZUNO_HANDLER_SYSEVENT,
	ZUNO_HANDLER_BATTERY
};
#define LEARN_TIMEOUT_INF 	0
#define LEARN_TIMEOUT_STOP 	0xFF

#define ZWAVE_CHANNEL_MAPPED_BIT 0x80

/* Transmit frame option flags */
#define TRANSMIT_OPTION_ACK                     0x01    /* request acknowledge from destination node */
#define TRANSMIT_OPTION_LOW_POWER               0x02    /* transmit at low output power level (1/3 of normal RF range)*/
#define TRANSMIT_OPTION_MULTICAST_AS_BROADCAST  0x02    /* The multicast frame should be send as a broadcast */
#define TRANSMIT_OPTION_AUTO_ROUTE              0x04    /* request retransmission via repeater nodes */
/* do not use response route - Even if available */
#define TRANSMIT_OPTION_NO_ROUTE                0x10
/* Use explore frame if needed */
#define TRANSMIT_OPTION_EXPLORE                 0x20
#define ZWAVE_PLUS_TX_OPTIONS 					(TRANSMIT_OPTION_ACK | TRANSMIT_OPTION_AUTO_ROUTE | TRANSMIT_OPTION_EXPLORE)

#endif // ZUNO_DEFINITIONS